[colors]
background = "#FCFBF9"
foreground = "#605A52"
cursor_bg = "#605A52" 
cursor_fg = "#FCFBF9"
selection_bg = "#DDDBD8"
selection_fg = "#605A52"
scrollbar_thumb = "#CDCBC7"

# This ensures they belong to the [colors] table
ansi = [
    "#5A544C", # Black
    "#8F5652", # Red
    "#747B4D", # Green
    "#886A44", # Yellow
    "#556995", # Blue
    "#83577D", # Magenta
    "#477A7B", # Cyan
    "#DDDBD8"  # White
]

brights = [
    "#9E9A95", # Bright Black
    "#8F5652", # Red
    "#747B4D", # Green
    "#886A44", # Yellow
    "#556995", # Blue
    "#AA5087", # Bright Magenta
    "#477A7B", # Cyan
    "#FCFBF9"  # Bright White
]

[colors.tab_bar]
background = "#DDDBD8"

[colors.tab_bar.active_tab]
bg_color = "#FCFBF9"   
fg_color = "#605A52"   
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "#ECEBE8"   
fg_color = "#9E9A95"   

[colors.tab_bar.new_tab]
bg_color = "#DDDBD8"
fg_color = "#9E9A95"

[metadata]
name = 'earl-grey'
author = 'Gavin Gray'
origin_url = 'github.com/gavinleroy/earl-grey.nvim'
